import requests

class Pokemon:
    def __init__(self, name):
        self.name = name

        url = f"https://pokeapi.co/api/v2/pokemon/{name}"
        self.data = requests.get(url).json()

    def show_info(self):
        print("Name:", self.data["name"])
        print("ID:", self.data["id"])
        print("Height:", self.data["height"])
        print("Weight:", self.data["weight"])
        print("stats:", self.data["stats"])
        print("types:", self.data["types"])
        print("abilities:", self.data["abilities"])
        print("moves:", self.data["moves"])
        print("sprites:", self.data["sprites"])


# Add Pokémon here
pokemons = [
    Pokemon("bulbasaur"),
    Pokemon("ivysaur"),
    Pokemon("venusaur"),
    Pokemon("charmander"),
    Pokemon("charmeleon"),
    Pokemon("charizard"),
    Pokemon("squirtle"),
    Pokemon("wartortle"),
    Pokemon("blastoise"),
    Pokemon("caterpie"),
    Pokemon("metapod"),
    Pokemon("butterfree"),
    Pokemon("weedle"),
    Pokemon("kakuna"),
    Pokemon("beedrill"),
    Pokemon("pidgey"),
    Pokemon("pidgeotto"),
    Pokemon("pidgeot"),
    Pokemon("rattata"),
    Pokemon("raticate"),
    Pokemon("spearow"),
    Pokemon("fearow"),
    Pokemon("ekans"),
    Pokemon("arbok"),
    Pokemon("pikachu"),
    Pokemon("raichu"),
    Pokemon("sandshrew"),
    Pokemon("sandslash"),
    Pokemon("nidoran-f"),
    Pokemon("nidorina"),
    Pokemon("nidoqueen"),
    Pokemon("nidoran-m"),
    Pokemon("nidorino"),
    Pokemon("nidoking"),
    Pokemon("clefairy"),
    Pokemon("clefable"),
    Pokemon("vulpix"),
    Pokemon("ninetales"),
    Pokemon("jigglypuff"),
    Pokemon("wigglytuff"),
    Pokemon("zubat"),
    Pokemon("golbat"),
    Pokemon("oddish"),
    Pokemon("gloom"),
    Pokemon("vileplume"),
    Pokemon("paras"),
    Pokemon("parasect"),
    Pokemon("venonat"),
    Pokemon("venomoth"),
    Pokemon("diglett"),
    Pokemon("dugtrio"),
    Pokemon("meowth"),
    Pokemon("persian"),
    Pokemon("psyduck"),
    Pokemon("golduck"),
    Pokemon("mankey"),
    Pokemon("primeape"),
    Pokemon("growlithe"),
    Pokemon("arcanine"),
    Pokemon("poliwag"),
    Pokemon("poliwhirl"),
    Pokemon("poliwrath"),
    Pokemon("abra"),
    Pokemon("kadabra"),
    Pokemon("alakazam"),
    Pokemon("machop"),
    Pokemon("machoke"),
    Pokemon("machamp"),
    Pokemon("bellsprout"),
    Pokemon("weepinbell"),
    Pokemon("victreebel"),
    Pokemon("tentacool"),
    Pokemon("tentacruel"),
    Pokemon("geodude"),
    Pokemon("graveler"),
    Pokemon("golem"),
    Pokemon("ponyta"),
    Pokemon("rapidash"),
    Pokemon("slowpoke"),
    Pokemon("slowbro"),
    Pokemon("magnemite"),
    Pokemon("magneton"),
    Pokemon("farfetchd"),
    Pokemon("doduo"),
    Pokemon("dodrio"),
    Pokemon("seel"),
    Pokemon("dewgong"),
    Pokemon("grimer"),
    Pokemon("muk"),
    Pokemon("shellder"),
    Pokemon("cloyster"),
    Pokemon("gastly"),
    Pokemon("haunter"),
    Pokemon("gengar"),
    Pokemon("onix"),
    Pokemon("drowzee"),
    Pokemon("hypno"),
    Pokemon("krabby"),
    Pokemon("kingler"),
    Pokemon("voltorb"),
    Pokemon("electrode"),
    Pokemon("exeggcute"),
    Pokemon("exeggutor"),
    Pokemon("cubone"),
    Pokemon("marowak"),
    Pokemon("hitmonlee"),
    Pokemon("hitmonchan"),
    Pokemon("lickitung"),
    Pokemon("koffing"),
    Pokemon("weezing"),
    Pokemon("rhyhorn"),
    Pokemon("rhydon"),
    Pokemon("chansey"),
    Pokemon("tangela"),
    Pokemon("kangaskhan"),
    Pokemon("horsea"),
    Pokemon("seadra"),
    Pokemon("goldeen"),
    Pokemon("seaking"),
    Pokemon("staryu"),
    Pokemon("starmie"),
    Pokemon("mr-mime"),
    Pokemon("scyther"),
    Pokemon("jynx"),
    Pokemon("electabuzz"),
    Pokemon("magmar"),
    Pokemon("pinsir"),
    Pokemon("tauros"),
    Pokemon("magikarp"),
    Pokemon("gyarados"),
    Pokemon("lapras"),
    Pokemon("ditto"),
    Pokemon("eevee"),
    Pokemon("vaporeon"),
    Pokemon("jolteon"),
    Pokemon("flareon"),
    Pokemon("porygon"),
    Pokemon("omanyte"),
    Pokemon("omastar"),
    Pokemon("kabuto"),
    Pokemon("kabutops"),
    Pokemon("aerodactyl"),
    Pokemon("snorlax"),
    Pokemon("articuno"),
    Pokemon("zapdos"),
    Pokemon("moltres"),
    Pokemon("dratini"),
    Pokemon("dragonair"),
    Pokemon("dragonite"),
    Pokemon("mewtwo"),
    Pokemon("mew")
]

# Show information
for pokemon in pokemons:
    pokemon.show_info()
    print()